### ISSUE TITLE
Bots in channel command

### ISSUE THREAD

**Issue by erulabs** [asdqwex/discobot#112]
It would be really nice to have a global command (ie: no hailing or botname) which all bots would reply to. IE:

Query:
`!bots?`

Reply:
`bot A: I'm connected from __IP_ADDRESS__ and answer to __BOT_NAME__`
`bot B: I'm connected from __IP_ADDRESS__ and answer to __BOT_NAME__`

**Comment by asdqwex** [comment]
:+1:
