### ISSUE TITLE
Production instance!

### ISSUE THREAD

**Issue by erulabs** [asdqwex/discobot#5]
Setup a production instance which is pushed to by successful commits to master branch!

**Comment by asdqwex** [comment]
:+1:

**Comment by erulabs** [comment]
PM me on discord if y'all need any hints to complete this 😍😎🤓

On Friday, January 22, 2016, Matthew Ellsworth notifications@github.com
wrote:

> [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/asdqwex/discobot/issues/5#issuecomment-173995188.

## 

---

{ "name": "Seandon Mooy",
  "email": "seandon.mooy@gmail.com”,
  "voice": "805-729-7655" }

**Comment by asdqwex** [comment]
@NeutralOne set this up in aws

**Comment by erulabs** [comment]
Right but it's not done - CI / CD? Monitoring?

On Tuesday, February 9, 2016, Matthew Ellsworth notifications@github.com
wrote:

> @NeutralOne https://github.com/NeutralOne set this up in aws
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/asdqwex/discobot/issues/5#issuecomment-182107158.

## 

---

{ "name": "Seandon Mooy",
  "email": "seandon.mooy@gmail.com”,
  "voice": "805-729-7655" }
